- name: Deploy Risk Assessment Project
  hosts: webserver
  become: yes

  tasks:
    - name: Stop existing backend container (if exists)
      shell: docker rm -f finance-dashboard-backend || true
      ignore_errors: yes

    - name: Deploy Backend
      shell: docker run -d --name finance-dashboard-backend -p 9192:9192 sejal28/risk-backend

    - name: Stop existing frontend container (if exists)
      shell: docker rm -f finance-dashboard-frontend || true
      ignore_errors: yes

    - name: Deploy Frontend
      shell: docker run -d --name finance-dashboard-frontend -p 3000:3000 sejal28/risk-frontend

    - name: Restart NGINX
      service:
        name: nginx
        state: restarted
