version: '3.8'

services:
  backend:
    image: sejal28/risk-backend
    build: ./Backend
    ports:
      - "9192:9192"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/current
      SPRING_DATASOURCE_USERNAME: sejal
      SPRING_DATASOURCE_PASSWORD: sejal
    networks:
      - risk-network
    depends_on:
      - mysql_db

  frontend:
    image: sejal28/risk-frontend
    build: ./Frontend
    ports:
      - "3000:3000"
    networks:
      - risk-network
    depends_on:
      - backend

  mysql_db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: risk_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - risk-network

networks:
  risk-network:

volumes:
  mysql_data:

